In [7]:
import numpy,pandas

pandas.concat\
  ([pandas.DataFrame(numpy.random.randint(4,size=(5,10)))
   ,pandas.DataFrame(numpy.random.randint(4,size=(5,10)))
   ]
).reset_index()

   index  0  1  2  3  4  5  6  7  8  9
0      0  2  0  3  3  2  2  2  3  0  3
1      1  1  3  1  1  3  3  2  3  3  1
2      2  0  2  2  2  2  2  1  1  0  3
3      3  3  3  1  3  3  2  1  0  0  3
4      4  1  3  1  2  0  2  0  2  2  1
5      0  0  3  2  2  2  2  0  2  0  2
6      1  0  1  0  3  3  0  0  2  0  1
7      2  1  2  0  0  3  2  2  3  0  0
8      3  3  3  0  0  0  0  0  3  0  3
9      4  2  3  1  2  3  1  3  1  3  2

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors
import csv
import json
import os
import pandas as pd
import multiprocessing

In [2]:
raw_train_data_1 = pd.read_csv('train_all.csv')
raw_train_data_2 = pd.read_csv('train_2.csv')
raw_train_data_1['is_final'] = 0
raw_train_data_2['is_final'] = 1


is_final = raw_train_data_1.pop('is_final')
raw_train_data_1.insert(25,'is_final',is_final)
is_final = raw_train_data_2.pop('is_final')
raw_train_data_2.insert(25,'is_final',is_final)

D:\Python\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (4,5,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
D:\Python\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [34]:
raw_train_data = pd.concat([raw_train_data_1,raw_train_data_2]).reset_index()
del raw_train_data['index']

In [35]:
raw_train_data

,service_type,is_mix_service,online_time,1_total_fee,2_total_fee,3_total_fee,4_total_fee,month_traffic,many_over_bill,contract_type,...,service1_caller_time,service2_caller_time,gender,age,complaint_level,former_complaint_num,former_complaint_fee,is_final,current_service,user_id
0,4,0,85,295.96,296.2,296,296.80,3813.614698,0,1,...,0.000000,564.366667,1,31,0,0,0.0,0,99999825,Gx4sJzcQog01UhZL
1,1,0,10,265.20,261.2,208.5,174.50,0.000000,1,0,...,355.166667,0.000000,1,30,0,0,0.0,0,90063345,kEXrhTiug93DIcLG
2,1,0,12,44.50,70.2,69,61.40,2598.397406,0,0,...,0.000000,98.416667,2,25,0,0,0.0,0,90109916,AouXr0EOUtSRdiYK
3,4,0,134,87.95,81.4,76,88.30,988.440563,0,0,...,74.483333,121.833333,1,44,0,0,0.0,0,89950166,Yds7U30hnRZDiLtb
4,4,0,84,317.04,314.08,435.51,413.05,5885.800642,0,1,...,35.100000,496.733333,1,31,2,1,0.0,0,99999825,OFDTSXrhN9Q2mbVw
5,4,0,46,36.00,36,36,37.20,218.003452,0,3,...,0.000000,14.633333,1,42,0,0,0.0,0,89950168,4qHSn3dkPzJTAjoG
6,1,0,12,33.60,32.7,38.7,45.70,0.000000,0,0,...,136.033333,0.000000,1,27,0,0,0.0,0,90063345,tXkjbzpTsZcxYPKG
7,4,0,109,116.00,116,116,116.00,635.946276,0,9,...,0.000000,310.733333,1,40,0,0,0.0,0,89950167,ro43b68MustgPyOR
8,4,0,30,73.95,91.42,66,65.95,230.273015,0,0,...,41.900000,82.916667,1,43,1,2,0.0,0,89950168,18e2VC0IJ7SkcKzF
9,1,0,7,89.00,91,90.6,126.10,0.000000,1,0,...,0.000000,101.833333,1,22,0,0,0.0,0,90155946,YCEo95zSZ08IJ3PW
10,4,0,47,42.00,42,42,42.00,0.000000,0,2,...,0.000000,9.200000,0,0,0,0,0.0,0,89950166,M9aTwUjbqQSYK8hN
11,4,0,51,76.10,156,116,107.30,3048.047233,0,9,...,0.000000,144.816667,1,43,0,0,0.0,0,89950166,cfGAgMWTJLt09VDs
12,4,0,59,123.30,175.2,110.95,178.00,683.888563,0,3,...,162.916667,465.683333,2,29,0,0,0.0,0,99999828,km0xTQGpIYZuXWyL
13,1,0,7,60.30,145.3,78.2,94.70,0.000000,1,0,...,1.916667,0.000000,1,27,0,0,0.0,0,90063345,d9L37fAwopQkWPYh
14,4,0,122,208.90,225.7,157,241.65,1490.740294,0,9,...,281.750000,724.900000,1,56,0,0,0.0,0,99999828,UXewZPdJbBiycY8Q
15,4,0,43,256.00,327.7,316.5,256.10,3882.650403,1,0,...,0.000000,98.616667,2,27,2,1,6000.0,0,99999828,Z5igARInaGBkjYdm
16,1,0,5,7.91,13.7,11.05,15.10,0.000000,1,0,...,0.000000,0.000000,1,44,0,0,0.0,0,90063345,gH7nkfV2a0cKPQT6
17,1,0,4,19.60,21.4,12.42,0.00,0.000000,0,0,...,0.900000,0.000000,1,17,0,0,0.0,0,90063345,wnYh1QfSNBcGMTJ5
18,4,1,65,84.35,98.05,76,76.00,1824.925221,0,9,...,47.116667,171.716667,2,30,0,0,0.0,0,89950166,zPhEjLIWi3dKV6GU
19,1,0,18,48.90,54.5,51.9,66.10,0.000000,1,0,...,3.333333,1.566667,1,24,0,0,0.0,0,90063345,JzrYtgsjF45bBun1
20,4,0,60,225.95,339.25,296.45,354.35,500.000000,0,1,...,0.000000,201.616667,1,36,0,0,0.0,0,99999826,rL402wVDpGPBfC8q
21,1,0,12,107.74,128.96,165.66,360.68,0.000000,1,0,...,21.266667,0.000000,1,27,0,0,0.0,0,90063345,CognwxZ2aJfv03c4
22,1,0,18,89.70,96.4,78.8,69.70,0.000000,1,0,...,388.533333,18.533333,1,26,0,0,0.0,0,90063345,QnU8PiaY63eAVlDr
23,4,0,72,126.10,126.5,126.5,126.85,2785.341695,0,3,...,0.000000,255.533333,1,49,0,0,0.0,0,99999827,xPRY6725k90KdyjW
24,4,0,30,71.00,71,79.64,95.86,14946.728151,0,9,...,0.000000,11.100000,1,30,0,0,0.0,0,89950168,qLyPkjf86sZdEtNg
25,4,0,74,139.93,163.48,154.8,177.61,5078.918970,0,9,...,0.000000,398.233333,1,31,0,0,0.0,0,99999828,IViSctryC8lTBvDj
26,4,1,51,75.95,79.55,96.03,76.00,591.061872,0,9,...,0.000000,165.100000,2,35,0,0,0.0,0,89950166,NAQc9BvmlKFjTgoC
27,4,0,18,146.00,146.1,146.2,146.00,6.233837,0,0,...,0.000000,39.966667,0,0,0,0,0.0,0,99999826,0QR3gvwTmBnHhlVZ
28,1,0,13,34.30,30.2,33.3,45.30,0.000000,1,0,...,0.000000,0.000000,1,26,0,0,0.0,0,90063345,D8Y21qN945kBieLd
29,1,0,14,105.90,176.7,91.4,162.50,0.000000,1,0,...,430.666667,0.000000,1,27,0,0,0.0,0,90063345,jzCO0UbDyAhJgeGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1118615,1,0,8,0.00,44.2,45.9,39.40,0.000000,1,0,...,0.000000,0.000000,1,19,0,0,0.0,1,90063345,zZUFXGCwVPs4fkuE
1118616,1,0,13,77.20,77.6,64.7,100.50,0.000000,1,0,...,0.000000,447.216667,1,21,0,0,0.0,1,90155946,zZUl3kgMtmx0QNVF
1118617,1,0,18,24.10,24.7,23.4,22.60,3283.793683,0,0,...,46.000000,37.466667,1,27,1,3,3000.0,1,90063345,zZUWvBTPlcd4DVsp
1118618,4,0,22,113.00,120.65,113,146.45,8117.064022,0,12,...,0.000000,253.950000,1,31,0,0,0.0,1,99999826,zZvaoeBJnCHOLl0R
1118619,1,0,8,39.20,22.9,31.1,58.50,0.000000,1,0,...,0.000000,0.000000,1,19,0,0,0.0,1,90063345,zZvp1N8Lcim9nDYs
1118620,1,0,6,28.30,37.1,34.9,18.08,0.000000,1,0,...,0.000000,0.633333,2,28,1,1,0.0,1,90063345,ZzVpFxwAc497E3im
1118621,1,0,14,62.50,55,41.1,53.40,0.000000,1,0,...,23.416667,0.000000,1,18,0,0,0.0,1,90063345,ZzvPSyJQCFhEx0jq
1118622,1,0,17,62.30,64.5,122.7,140.40,100.000000,1,0,...,70.900000,0.000000,1,18,0,0,0.0,1,90063345,Zzw0Oryqo2FIR7dL
1118623,4,1,47,106.00,106,106,106.00,0.000000,0,1,...,0.000000,165.633333,2,37,0,0,0.0,1,89950167,ZzWfc3nX1m8YpBKx
1118624,1,0,14,76.50,56.9,103.8,53.50,0.000000,1,0,...,10.783333,0.000000,1,20,0,0,0.0,1,90063345,zZWgVTH1ANIGBt5M
1118625,1,0,8,21.90,93.9,48.1,53.00,0.000000,1,0,...,0.000000,0.000000,1,20,0,0,0.0,1,90063345,zZWl4bPK6oxc9p8e
1118626,1,0,16,53.20,66.1,67.2,52.80,0.000000,1,0,...,28.066667,0.000000,1,21,0,0,0.0,1,90063345,ZzwM31NIcktnyu4v
1118627,1,0,6,42.90,19.9,22.5,31.20,0.000000,1,0,...,5.150000,0.000000,1,38,0,0,0.0,1,90063345,Zzwr2GbCW5h9X3um
1118628,4,0,136,96.60,87.15,81,81.00,292.604599,0,1,...,52.050000,135.616667,1,39,0,0,0.0,1,89950166,ZzwSrNX4fRhuEPI7
1118629,1,0,13,81.10,76.2,56.6,87.00,500.000000,1,0,...,56.366667,0.000000,1,23,3,1,0.0,1,90063345,ZzwvFhsyJ6qSdV43
1118630,1,0,5,38.00,89.6,48.1,23.09,0.000000,1,0,...,32.400000,0.000000,1,31,0,0,0.0,1,90063345,zZwxhra2Pg6AjCB7
1118631,1,0,17,66.10,70.1,57,79.50,0.000000,1,0,...,185.666667,0.000000,2,27,0,0,0.0,1,90063345,zZx7jacCUTvSgkXB
1118632,4,0,85,166.00,166,166,168.85,0.000000,0,1,...,0.000000,201.683333,1,37,0,0,0.0,1,99999827,ZzXOB408E1wuNmAf
1118633,1,0,6,62.00,71,87.5,80.10,0.000000,1,0,...,75.200000,61.433333,2,23,0,0,0.0,1,90063345,zZxpw2uFSiAUyRgX
1118634,1,0,16,28.00,37.6,32.2,40.00,0.000000,1,0,...,55.950000,86.633333,2,47,0,0,0.0,1,90063345,ZzxReWtmyudU8piD
1118635,1,0,7,59.50,131.6,111.1,71.80,0.000000,1,0,...,91.000000,0.000000,1,25,0,0,0.0,1,90063345,ZzXvM8stdihreWEa
1118636,1,0,17,66.10,70.5,69.7,64.70,0.000000,1,0,...,0.000000,66.200000,1,19,0,0,0.0,1,90063345,zZy4Vv8eGF5Y0RCH
1118637,1,0,4,79.70,43.58,25.05,3.82,0.000000,1,0,...,122.283333,0.000000,2,51,0,0,0.0,1,90063345,zZyaY6T9ELkFmRtI
1118638,1,0,17,66.70,65.1,67.6,60.30,582.429632,1,0,...,24.250000,0.000000,1,21,0,0,0.0,1,90063345,ZzyCMfn6pYbL90mW
1118639,1,0,6,24.00,39.7,24.33,15.89,0.000000,0,0,...,0.000000,0.783333,1,29,0,0,0.0,1,90063345,ZzYEq0OPVMl8CDFH
1118640,1,0,4,66.30,31.03,32,14.32,0.000000,1,0,...,41.600000,0.000000,1,32,0,0,0.0,1,90063345,zZyFnfY6usXQLHKc
1118641,1,0,8,46.00,36,66.4,66.10,3894.005960,0,0,...,0.000000,4.383333,1,28,1,1,0.0,1,90109916,ZzyPo1x30Up2mqcl
1118642,1,0,5,42.00,20.91,18.65,22.30,0.000000,1,0,...,37.183333,0.000000,2,21,0,0,0.0,1,90063345,zZYs40pnDBTyE6Mu
1118643,1,0,13,36.90,36,42.1,46.10,1204.740172,0,0,...,4.066667,76.166667,2,28,0,0,0.0,1,90109916,zZyTBEviMdSClgoX
1118644,1,0,15,65.10,56.1,57.6,70.50,0.000000,1,0,...,44.066667,0.000000,1,19,0,0,0.0,1,90063345,zZYVcXqTRGwAEe26

In [10]:
raw_train_data['service_type'][300000]

300000    4
300000    1
Name: service_type, dtype: int64

In [36]:
# Columns (4,5,20,21) have mixed types.是由于\\N 故找出训练集里的\\N
print(raw_train_data[raw_train_data[raw_train_data.columns[4]].isin([r'\N'])].index)
print(raw_train_data[raw_train_data[raw_train_data.columns[5]].isin([r'\N'])].index)
print(raw_train_data[raw_train_data[raw_train_data.columns[20]].isin([r'\N'])].index)
print(raw_train_data[raw_train_data[raw_train_data.columns[21]].isin([r'\N'])].index)
for i in range(26):
    print(raw_train_data[raw_train_data[raw_train_data.columns[i]].isin([r'\N'])].index)

Int64Index([600438, 746969, 751078, 777226, 790581, 821357, 850855, 962596], dtype='int64')
Int64Index([600438, 642033, 777226, 790581, 872915, 937303], dtype='int64')
Int64Index([140569, 232620], dtype='int64')
Int64Index([140569, 232620], dtype='int64')
Int64Index([], dtype='int64')
Int64Index([], dtype='int64')
Int64Index([], dtype='int64')
Int64Index([], dtype='int64')
Int64Index([600438, 746969, 751078, 777226, 790581, 821357, 850855, 962596], dtype='int64')

D:\Python\Anaconda3\lib\site-packages\numpy\lib\arraysetops.py:522: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

Int64Index([600438, 642033, 777226, 790581, 872915, 937303], dtype='int64')
Int64Index([], dtype='int64')
Int64Index([], dtype='int64')
Int64Index([], dtype='int64')
Int64Index([], dtype='int64')
Int64Index([], dtype='int64')
Int64Index([], dtype='int64')
Int64Index([], dtype='int64')
Int64Index([], dtype='int64')
Int64Index([], dtype='int64')
Int64Index([], dtype='int64')
Int64Index([], dtype='int64')
Int64Index([], dtype='int64')
Int64Index([], dtype='int64')
Int64Index([], dtype='int64')
Int64Index([140569, 232620], dtype='int64')
Int64Index([140569, 232620], dtype='int64')
Int64Index([], dtype='int64')
Int64Index([], dtype='int64')
Int64Index([], dtype='int64')
Int64Index([], dtype='int64')

In [37]:
# 可以直接扔掉训练集里的\\N
print(raw_train_data.shape)
#raw_train_data.drop(raw_train_data.index[[600438,642033,140569,232620]],inplace=True)
raw_train_data.drop(raw_train_data.index[[600438,642033, 746969, 751078, 777226, 790581, 821357, 850855,872915, 937303, 962596,140569, 232620]],inplace=True)
print(raw_train_data.shape)

(1118645, 28)
(1118632, 28)

In [38]:
# 去除重复数据
raw_train_data.drop_duplicates(subset=['online_time','1_total_fee','2_total_fee','3_total_fee','4_total_fee','month_traffic',
                                       'last_month_traffic','local_trafffic_month','local_caller_time','service1_caller_time',
                                       'service2_caller_time'], inplace=True)
print(raw_train_data.shape)

(1062467, 28)

In [39]:
#训练集数据和标签 pandas
raw_x = raw_train_data.iloc[:,0:26].astype(float)
raw_y = raw_train_data.iloc[:,26].astype(int)

#### 特征工程

In [40]:
# 原始类别特征
raw_class_feature = ['service_type', 'complaint_level', 'contract_type', 'gender', 'is_mix_service',
                    'is_promise_low_consume',
                    'many_over_bill', 'net_service']
# 原始数值特征
raw_num_feature = ['1_total_fee', '2_total_fee', '3_total_fee', '4_total_fee',
                    'age', 'contract_time',
                    'former_complaint_fee', 'former_complaint_num',
                    'last_month_traffic', 'local_caller_time', 'local_trafffic_month', 'month_traffic',
                    'online_time', 'pay_num', 'pay_times', 'service1_caller_time', 'service2_caller_time']

In [41]:
# 新增！差值特征
diff_feature_list = ['diff_total_fee_1', 'diff_total_fee_2', 'diff_total_fee_3', 'last_month_traffic_rest',
                     'rest_traffic_ratio',
                     'total_fee_mean', 'total_fee_max', 'total_fee_min', 'total_caller_time', 'service2_caller_ratio',
                     'local_caller_ratio',
                     'total_month_traffic', 'month_traffic_ratio', 'last_month_traffic_ratio', 'pay_num_1_total_fee',
                     '1_total_fee_call_fee', '1_total_fee_call2_fee', '1_total_fee_trfc_fee']

def add_diff_feature(data):
    data['diff_total_fee_1'] = data['1_total_fee'] - data['2_total_fee']
    data['diff_total_fee_2'] = data['2_total_fee'] - data['3_total_fee']
    data['diff_total_fee_3'] = data['3_total_fee'] - data['4_total_fee']

    data['pay_num_1_total_fee'] = data['pay_num'] - data['1_total_fee']

    data['last_month_traffic_rest'] = data['month_traffic'] - data['last_month_traffic']
    data['last_month_traffic_rest'][data['last_month_traffic_rest'] < 0] = 0
    data['rest_traffic_ratio'] = (data['last_month_traffic_rest'] * 15 / 1024) / data['1_total_fee']

    total_fee = []
    for i in range(1, 5):
        total_fee.append(str(i) + '_total_fee')
    data['total_fee_mean'] = data[total_fee].mean(1)
    data['total_fee_max'] = data[total_fee].max(1)
    data['total_fee_min'] = data[total_fee].min(1)

    data['total_caller_time'] = data['service2_caller_time'] + data['service1_caller_time']
    data['service2_caller_ratio'] = data['service2_caller_time'] / data['total_caller_time']
    data['local_caller_ratio'] = data['local_caller_time'] / data['total_caller_time']

    data['total_month_traffic'] = data['local_trafffic_month'] + data['month_traffic']
    data['month_traffic_ratio'] = data['month_traffic'] / data['total_month_traffic']
    data['last_month_traffic_ratio'] = data['last_month_traffic'] / data['total_month_traffic']

    data['1_total_fee_call_fee'] = data['1_total_fee'] - data['service1_caller_time'] * 0.15
    data['1_total_fee_call2_fee'] = data['1_total_fee'] - data['service2_caller_time'] * 0.15
    data['1_total_fee_trfc_fee'] = data['1_total_fee'] - (
    data['month_traffic'] - 2 * data['last_month_traffic']) * 0.3

In [42]:
# 训练集 新增 差值特征：
print(raw_x.shape)
add_diff_feature(raw_x)
print(raw_x.shape)
print(raw_x.columns)
raw_x.head()

(1062467, 26)
(1062467, 44)
Index(['service_type', 'is_mix_service', 'online_time', '1_total_fee',
       '2_total_fee', '3_total_fee', '4_total_fee', 'month_traffic',
       'many_over_bill', 'contract_type', 'contract_time',
       'is_promise_low_consume', 'net_service', 'pay_times', 'pay_num',
       'last_month_traffic', 'local_trafffic_month', 'local_caller_time',
       'service1_caller_time', 'service2_caller_time', 'gender', 'age',
       'complaint_level', 'former_complaint_num', 'former_complaint_fee',
       'is_final', 'diff_total_fee_1', 'diff_total_fee_2', 'diff_total_fee_3',
       'pay_num_1_total_fee', 'last_month_traffic_rest', 'rest_traffic_ratio',
       'total_fee_mean', 'total_fee_max', 'total_fee_min', 'total_caller_time',
       'service2_caller_ratio', 'local_caller_ratio', 'total_month_traffic',
       'month_traffic_ratio', 'last_month_traffic_ratio',
       '1_total_fee_call_fee', '1_total_fee_call2_fee',
       '1_total_fee_trfc_fee'],
      dtype='object')

,service_type,is_mix_service,online_time,1_total_fee,2_total_fee,3_total_fee,4_total_fee,month_traffic,many_over_bill,contract_type,...,total_fee_min,total_caller_time,service2_caller_ratio,local_caller_ratio,total_month_traffic,month_traffic_ratio,last_month_traffic_ratio,1_total_fee_call_fee,1_total_fee_call2_fee,1_total_fee_trfc_fee
0,4.0,0.0,85.0,295.96,296.20,296.00,296.80,3813.614698,0.0,1.0,...,295.96,564.366667,1.000000,0.191542,5205.653206,0.732591,0.786837,295.9600,211.3050,1609.475590
1,1.0,0.0,10.0,265.20,261.20,208.50,174.50,0.000000,1.0,0.0,...,174.50,355.166667,0.000000,0.676021,62852.509718,0.000000,0.000000,211.9250,265.2000,265.200000
2,1.0,0.0,12.0,44.50,70.20,69.00,61.40,2598.397406,0.0,0.0,...,44.50,98.416667,1.000000,0.281118,4533.639510,0.573137,0.000000,44.5000,29.7375,-735.019222
3,4.0,0.0,134.0,87.95,81.40,76.00,88.30,988.440563,0.0,0.0,...,76.00,196.316667,0.620596,0.457934,1977.001638,0.499970,0.018885,76.7775,69.6750,-186.180314
4,4.0,0.0,84.0,317.04,314.08,435.51,413.05,5885.800642,0.0,1.0,...,314.08,531.833333,0.934002,0.000000,5885.800642,1.000000,0.561647,311.7750,242.5300,534.744484

In [10]:
#Word2Vec特征处理

#读入测试数据
raw_test_data = pd.read_csv('republish_test.csv')
# Columns (4,5) have mixed types.是由于\\N 不能直接扔掉，替换为999
raw_test_data = raw_test_data.replace('\\N', 999)
#划分测试数据和id pandas
raw_test = raw_test_data.iloc[:,0:25].astype(float)
raw_id = raw_test_data.iloc[:,25]

sentence = []
for line in list(raw_x[['1_total_fee', '2_total_fee', '3_total_fee', '4_total_fee']].values):
    sentence.append([str(float(l)) for idx, l in enumerate(line)])
print(len(sentence))

for line in list(raw_test[['1_total_fee', '2_total_fee', '3_total_fee', '4_total_fee']].values):
    sentence.append([str(float(l)) for idx, l in enumerate(line)])
print(len(sentence))
print(sentence[0])

D:\Python\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

697366
897366
['295.96', '296.2', '296.0', '296.8']

In [12]:
from gensim.models import Word2Vec
L = 10
print('training...')
model = Word2Vec(sentence, size=L, window=2, min_count=1, workers=multiprocessing.cpu_count(),
                 iter=10)
print('outputing...')

D:\Python\Anaconda3\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")

training...
outputing...

In [13]:
def add_w2v_feature(input_x):
    total_df = pd.DataFrame()
    w2v_features = []
    add_features = pd.DataFrame()
    total_features = pd.DataFrame()
    for fea in ['1_total_fee', '2_total_fee', '3_total_fee', '4_total_fee']:
    #for fea in ['1_total_fee']:
        values = []
        for line in list(input_x[fea].values):
            values.append(line)
        values = set(values)
        w2v = []
        for i in values:
            a = [i]
            a.extend(model[str(float(i))])
            w2v.append(a)
        out_df = pd.DataFrame(w2v)

        name = [fea]
        for i in range(L):
            name.append(name[0] + 'W' + str(i))
        out_df.columns = name
    
        out_df = out_df.drop_duplicates([fea])

        add_features = pd.DataFrame(input_x[fea])
        add_features = pd.merge(add_features, out_df, on=fea, how='left')
        del add_features[fea]
        if total_features.empty :
            total_features = add_features
        else :
            total_features = total_features.join(add_features)
        print(len(total_features))
    total_features
    input_x = input_x.join(total_features)
    input_x.head()
    return input_x
    
raw_x = add_w2v_feature(raw_x)

D:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  from ipykernel import kernelapp as app

697366
697366
697366
697366

In [43]:
raw_x.head()

,service_type,is_mix_service,online_time,1_total_fee,2_total_fee,3_total_fee,4_total_fee,month_traffic,many_over_bill,contract_type,...,total_fee_min,total_caller_time,service2_caller_ratio,local_caller_ratio,total_month_traffic,month_traffic_ratio,last_month_traffic_ratio,1_total_fee_call_fee,1_total_fee_call2_fee,1_total_fee_trfc_fee
0,4.0,0.0,85.0,295.96,296.20,296.00,296.80,3813.614698,0.0,1.0,...,295.96,564.366667,1.000000,0.191542,5205.653206,0.732591,0.786837,295.9600,211.3050,1609.475590
1,1.0,0.0,10.0,265.20,261.20,208.50,174.50,0.000000,1.0,0.0,...,174.50,355.166667,0.000000,0.676021,62852.509718,0.000000,0.000000,211.9250,265.2000,265.200000
2,1.0,0.0,12.0,44.50,70.20,69.00,61.40,2598.397406,0.0,0.0,...,44.50,98.416667,1.000000,0.281118,4533.639510,0.573137,0.000000,44.5000,29.7375,-735.019222
3,4.0,0.0,134.0,87.95,81.40,76.00,88.30,988.440563,0.0,0.0,...,76.00,196.316667,0.620596,0.457934,1977.001638,0.499970,0.018885,76.7775,69.6750,-186.180314
4,4.0,0.0,84.0,317.04,314.08,435.51,413.05,5885.800642,0.0,1.0,...,314.08,531.833333,0.934002,0.000000,5885.800642,1.000000,0.561647,311.7750,242.5300,534.744484

In [70]:
count_feature_list = []
def feature_count(data, features=[]):
    if len(set(features)) != len(features):
        print('equal feature !!!!')
        return data
    new_feature = 'count'
    for i in features:
        new_feature += '_' + i.replace('add_', '')
    temp = data.groupby(features).size().reset_index().rename(columns={0: new_feature})
    data = data.merge(temp, 'left', on=features)
    count_feature_list.append(new_feature)
    if 'service_type' in features:
        temp_2 = train_first.groupby(features).size().reset_index().rename(columns={0: 'train_' + new_feature})
        data = data.merge(temp_2, 'left', on=features)
        count_feature_list.append('train_' + new_feature)
    return data

def add_feature_count(raw_x):
    raw_x = feature_count(raw_x, ['1_total_fee'])
    raw_x = feature_count(raw_x, ['2_total_fee'])
    raw_x = feature_count(raw_x, ['3_total_fee'])
    raw_x = feature_count(raw_x, ['4_total_fee'])

    raw_x = feature_count(raw_x, ['former_complaint_fee'])

    raw_x = feature_count(raw_x, ['pay_num'])
    raw_x = feature_count(raw_x, ['contract_time'])
    raw_x = feature_count(raw_x, ['last_month_traffic'])
    raw_x = feature_count(raw_x, ['online_time'])
    
    #raw_x = feature_count(raw_x, ['contract_type', '1_total_fee'])
    #raw_x = feature_count(raw_x, ['contract_type', '2_total_fee'])
    #raw_x = feature_count(raw_x, ['contract_type', '3_total_fee'])
    #raw_x = feature_count(raw_x, ['contract_type', '4_total_fee'])

    #raw_x = feature_count(raw_x, ['contract_type', 'former_complaint_fee'])

    #raw_x = feature_count(raw_x, ['contract_type', 'pay_num'])
    #raw_x = feature_count(raw_x, ['contract_type', 'contract_time'])
    #raw_x = feature_count(raw_x, ['contract_type', 'last_month_traffic'])
    #raw_x = feature_count(raw_x, ['contract_type', 'online_time'])
    return raw_x
raw_x = add_feature_count(raw_x)

In [33]:
raw_x.head()

,index,service_type,is_mix_service,online_time,1_total_fee,2_total_fee,3_total_fee,4_total_fee,month_traffic,many_over_bill,...,total_fee_min,total_caller_time,service2_caller_ratio,local_caller_ratio,total_month_traffic,month_traffic_ratio,last_month_traffic_ratio,1_total_fee_call_fee,1_total_fee_call2_fee,1_total_fee_trfc_fee
0,0.0,4.0,0.0,85.0,295.96,296.20,296.00,296.80,3813.614698,0.0,...,295.96,564.366667,1.000000,0.191542,5205.653206,0.732591,0.786837,295.9600,211.3050,1609.475590
1,1.0,1.0,0.0,10.0,265.20,261.20,208.50,174.50,0.000000,1.0,...,174.50,355.166667,0.000000,0.676021,62852.509718,0.000000,0.000000,211.9250,265.2000,265.200000
2,2.0,1.0,0.0,12.0,44.50,70.20,69.00,61.40,2598.397406,0.0,...,44.50,98.416667,1.000000,0.281118,4533.639510,0.573137,0.000000,44.5000,29.7375,-735.019222
3,3.0,4.0,0.0,134.0,87.95,81.40,76.00,88.30,988.440563,0.0,...,76.00,196.316667,0.620596,0.457934,1977.001638,0.499970,0.018885,76.7775,69.6750,-186.180314
4,4.0,4.0,0.0,84.0,317.04,314.08,435.51,413.05,5885.800642,0.0,...,314.08,531.833333,0.934002,0.000000,5885.800642,1.000000,0.561647,311.7750,242.5300,534.744484

In [44]:
#训练集数据和标签 从pandas到numpy array
x = np.array(raw_x,dtype=np.float64)
y = np.array(raw_y,dtype=np.int64)

In [45]:
num_features = len(raw_x.columns)
print(num_features)

44

In [46]:
x[4]

array([ 4.00000000e+00,  0.00000000e+00,  8.40000000e+01,  3.17040000e+02,
        3.14080000e+02,  4.35510000e+02,  4.13050000e+02,  5.88580064e+03,
        0.00000000e+00,  1.00000000e+00,  2.40000000e+01,  0.00000000e+00,
        4.00000000e+00,  1.20000000e+01,  1.00003000e+03,  3.30574113e+03,
        0.00000000e+00,  0.00000000e+00,  3.51000000e+01,  4.96733333e+02,
        1.00000000e+00,  3.10000000e+01,  2.00000000e+00,  1.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  2.96000000e+00, -1.21430000e+02,
        2.24600000e+01,  6.82990000e+02,  2.58005951e+03,  1.19208430e-01,
        3.69920000e+02,  4.35510000e+02,  3.14080000e+02,  5.31833333e+02,
        9.34001880e-01,  0.00000000e+00,  5.88580064e+03,  1.00000000e+00,
        5.61646805e-01,  3.11775000e+02,  2.42530000e+02,  5.34744484e+02])

In [47]:
#筛选出service_type==1的训练数据
x_1 = x[np.where(x[:,0]==1)]
x_1 = x_1[:,1:num_features]
y_1 = y[np.where(x[:,0]==1)]
#筛选出service_type==4的训练数据
x_4 = x[np.where(x[:,0]==4)]
x_4 = x_4[:,1:num_features]
y_4 = y[np.where(x[:,0]==4)]

print('type=1 标签分布情况：')
print(pd.value_counts(y_1))
print('type=4 标签分布情况：')
print(pd.value_counts(y_4))

type=1 标签分布情况：
90063345    491372
90109916     54983
90155946     33798
dtype: int64
type=4 标签分布情况：
89950166    147953
89950167    104418
99999828     64486
89950168     38323
99999827     37417
99999826     35025
99999830     30826
99999825     23830
dtype: int64

In [48]:
#划分出训练集和验证集
from sklearn.model_selection import train_test_split
x_train_1, x_validation_1, y_train_1, y_validation_1 = train_test_split(x_1, y_1, test_size=0.10, random_state=6)
x_train_4, x_validation_4, y_train_4, y_validation_4 = train_test_split(x_4, y_4, test_size=0.10, random_state=6)

#### 处理测试数据

In [55]:
#读入测试数据
raw_test_data = pd.read_csv('republish_test.csv')

D:\Python\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [56]:
# Columns (4,5) have mixed types.是由于\\N 不能直接扔掉，替换为999
raw_test_data = raw_test_data.replace('\\N', 999)

In [57]:
#划分测试数据和id pandas
raw_test = raw_test_data.iloc[:,0:25].astype(float)
raw_id = raw_test_data.iloc[:,25]

In [28]:
# 测试集 新增 差值特征：
print(raw_test.shape)
add_diff_feature(raw_test)
add_w2v_feature(raw_test)
print(raw_test.shape)
print(raw_test.columns)
raw_test.head()

(200000, 43)

D:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  from ipykernel import kernelapp as app

KeyError: "word '383.31' not in vocabulary"

In [58]:
raw_test['is_final'] = 0
is_final = raw_test.pop('is_final')
raw_test.insert(25,'is_final',is_final)

add_diff_feature(raw_test)
raw_test.head()

D:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,service_type,is_mix_service,online_time,1_total_fee,2_total_fee,3_total_fee,4_total_fee,month_traffic,many_over_bill,contract_type,...,total_fee_min,total_caller_time,service2_caller_ratio,local_caller_ratio,total_month_traffic,month_traffic_ratio,last_month_traffic_ratio,1_total_fee_call_fee,1_total_fee_call2_fee,1_total_fee_trfc_fee
0,1.0,0.0,18.0,50.4,108.2,118.9,177.7,300.0,1.0,0.0,...,50.4,37.783333,0.0,1.000000,2939.084859,0.102073,0.0,44.7325,50.4,-39.6
1,1.0,0.0,16.0,84.4,78.2,56.9,80.4,0.0,1.0,0.0,...,56.9,41.833333,0.0,0.123904,39155.458728,0.000000,0.0,78.1250,84.4,84.4
2,1.0,0.0,9.0,80.5,75.6,74.3,93.4,0.0,1.0,0.0,...,74.3,67.666667,0.0,0.943842,48755.950069,0.000000,0.0,70.3500,80.5,80.5
3,1.0,0.0,15.0,69.3,63.8,50.2,62.2,0.0,1.0,0.0,...,50.2,11.483333,0.0,0.500726,0.000000,NaN,NaN,67.5775,69.3,69.3
4,1.0,0.0,18.0,37.3,33.2,19.8,19.5,0.0,1.0,0.0,...,19.5,4.383333,0.0,0.923954,5257.352050,0.000000,0.0,36.6425,37.3,37.3

In [20]:
raw_test = add_w2v_feature(raw_test)
raw_test.head()

D:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  from ipykernel import kernelapp as app

200000
200000
200000
200000

,service_type,is_mix_service,online_time,1_total_fee,2_total_fee,3_total_fee,4_total_fee,month_traffic,many_over_bill,contract_type,...,4_total_feeW0,4_total_feeW1,4_total_feeW2,4_total_feeW3,4_total_feeW4,4_total_feeW5,4_total_feeW6,4_total_feeW7,4_total_feeW8,4_total_feeW9
0,1.0,0.0,18.0,50.4,108.2,118.9,177.7,300.0,1.0,0.0,...,-0.218862,-0.314282,-0.205490,-1.576776,-0.783220,0.957503,0.879186,-0.100822,-2.191919,-1.484912
1,1.0,0.0,16.0,84.4,78.2,56.9,80.4,0.0,1.0,0.0,...,0.753076,-0.847917,-2.803092,-2.508464,-1.753684,0.465635,1.978619,-1.124180,1.288662,0.489146
2,1.0,0.0,9.0,80.5,75.6,74.3,93.4,0.0,1.0,0.0,...,0.836588,-0.219469,-3.156484,-1.951655,-2.404257,0.593454,1.551570,-0.349830,0.240193,-0.193000
3,1.0,0.0,15.0,69.3,63.8,50.2,62.2,0.0,1.0,0.0,...,1.747039,-0.594882,-2.492915,-3.285303,-1.161983,-0.746888,2.036673,-2.073806,1.331888,1.467112
4,1.0,0.0,18.0,37.3,33.2,19.8,19.5,0.0,1.0,0.0,...,1.839313,-2.742340,0.519245,-0.539645,-3.445933,1.072672,2.856521,-1.826846,1.955586,3.068541

In [80]:
raw_test = add_feature_count(raw_test)
raw_test.head()

,service_type,is_mix_service,online_time,1_total_fee,2_total_fee,3_total_fee,4_total_fee,month_traffic,many_over_bill,contract_type,...,1_total_fee_trfc_fee,count_1_total_fee,count_2_total_fee,count_3_total_fee,count_4_total_fee,count_former_complaint_fee,count_pay_num,count_contract_time,count_last_month_traffic,count_online_time
0,1.0,0.0,18.0,50.4,108.2,118.9,177.7,300.0,1.0,0.0,...,-39.6,247,52,17,13,196199,14252,147221,156073,12017
1,1.0,0.0,16.0,84.4,78.2,56.9,80.4,0.0,1.0,0.0,...,84.4,143,136,209,89,196199,4978,147221,156073,8074
2,1.0,0.0,9.0,80.5,75.6,74.3,93.4,0.0,1.0,0.0,...,80.5,181,133,110,69,196199,4209,147221,156073,11339
3,1.0,0.0,15.0,69.3,63.8,50.2,62.2,0.0,1.0,0.0,...,69.3,186,199,257,201,196199,14252,147221,156073,8262
4,1.0,0.0,18.0,37.3,33.2,19.8,19.5,0.0,1.0,0.0,...,37.3,154,80,78,59,196199,6104,147221,156073,12017

In [59]:
x_test = np.array(raw_test,dtype=np.float64)
id_test = np.array(raw_id)

#### 输出到文件

In [60]:
#输出到文件
data_dir = 'preprocessed_add_diff'
if not os.path.exists(data_dir):
    os.mkdir(data_dir)

np.save(os.path.join(data_dir,'x_train_1.npy'),x_train_1)
np.save(os.path.join(data_dir,'x_validation_1.npy'),x_validation_1)
np.save(os.path.join(data_dir,'y_train_1.npy'),y_train_1)
np.save(os.path.join(data_dir,'y_validation_1.npy'),y_validation_1)

np.save(os.path.join(data_dir,'x_train_4.npy'),x_train_4)
np.save(os.path.join(data_dir,'x_validation_4.npy'),x_validation_4)
np.save(os.path.join(data_dir,'y_train_4.npy'),y_train_4)
np.save(os.path.join(data_dir,'y_validation_4.npy'),y_validation_4)

np.save(os.path.join(data_dir,'x_test.npy'),x_test)
np.save(os.path.join(data_dir,'id_test.npy'),id_test)

In [19]:
#从文件load到numpy array
data_dir = 'preprocessed_add_diff'
#读入service_type==1的训练数据
x_train_1 = np.load(os.path.join(data_dir,'x_train_1.npy'))
x_validation_1 = np.load(os.path.join(data_dir,'x_validation_1.npy'))
y_train_1 = np.load(os.path.join(data_dir,'y_train_1.npy'))
y_validation_1 = np.load(os.path.join(data_dir,'y_validation_1.npy'))
#读入service_type==4的训练数据
x_train_4 = np.load(os.path.join(data_dir,'x_train_4.npy'))
x_validation_4 = np.load(os.path.join(data_dir,'x_validation_4.npy'))
y_train_4 = np.load(os.path.join(data_dir,'y_train_4.npy'))
y_validation_4 = np.load(os.path.join(data_dir,'y_validation_4.npy'))
#读入测试数据
x_test = np.load(os.path.join(data_dir,'x_test.npy'))
id_test = np.load(os.path.join(data_dir,'id_test.npy'))

print(x_train_1[0])
print(x_test[0])
print(id_test[0])

[ 0.00000000e+00  9.00000000e+00  6.62000000e+01  8.45000000e+01
  5.55000000e+01  6.41000000e+01  0.00000000e+00  1.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  4.00000000e+00
  1.00000000e+00  3.00000000e+01  0.00000000e+00  3.67536019e+03
  8.29000000e+01  1.03550000e+02  1.63333333e+01  1.00000000e+00
  2.60000000e+01  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -1.83000000e+01  2.90000000e+01 -8.60000000e+00 -3.62000000e+01
  0.00000000e+00  0.00000000e+00  6.75750000e+01  8.45000000e+01
  5.55000000e+01  1.19883333e+02  1.36243570e-01  6.91505630e-01
  3.67536019e+03  0.00000000e+00  0.00000000e+00  5.06675000e+01
  6.37500000e+01  6.62000000e+01]
[ 1.00000000e+00  0.00000000e+00  1.80000000e+01  5.04000000e+01
  1.08200000e+02  1.18900000e+02  1.77700000e+02  3.00000000e+02
  1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  4.00000000e+00  2.00000000e+00  6.00000000e+01  0.00000000e+00
  2.63908486e+03  3.77833333e+01  3.77833333e+01  0.00000000e+00
  1.00000000e+00  1.90000000e+01  0.00000000e+00  0.00000000e+00
  0.00000000e+00 -5.78000000e+01 -1.07000000e+01 -5.88000000e+01
  9.60000000e+00  3.00000000e+02  8.71930804e-02  1.13800000e+02
  1.77700000e+02  5.04000000e+01  3.77833333e+01  0.00000000e+00
  1.00000000e+00  2.93908486e+03  1.02072589e-01  0.00000000e+00
  4.47325000e+01  5.04000000e+01 -3.96000000e+01]
012pSke7DsCrR985